"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowRight, ArrowUp, BarChart3, Bot, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Code2, Command, Layers3, Menu, Moon, MousePointer2, Play, Quote, ShieldCheck, Sparkles, Sun, Users2, Wand2, X, Zap } from "lucide-react";

const navLinks = [["Features","features"],["How it works","how-it-works"],["Solutions","solutions"],["Pricing","pricing"],["FAQ","faq"]];
const features = [
  [Bot,"AI task copilot","Turn loose ideas into clear tasks, owners and timelines in seconds."],
  [Zap,"Smart automation","Automate handoffs, updates and repetitive work without writing code."],
  [Users2,"Live collaboration","Plan, comment and make decisions together in one focused workspace."],
  [BarChart3,"Instant insights","See workload, progress and blockers before they slow your team down."],
  [Layers3,"Flexible workflows","Switch between list, board and timeline views as your work changes."],
  [ShieldCheck,"Enterprise security","Keep work protected with role controls, encryption and audit logs."]
] as const;
const solutions = [
  [Sparkles,"Product teams","From idea to launch","Connect roadmaps, specs and release plans so every contributor sees what matters next.","violet"],
  [Wand2,"Marketing","Campaigns without chaos","Plan content, route approvals and track performance from a single campaign command center.","cyan"],
  [Code2,"Engineering","Ship with clarity","Turn priorities into sprints, surface blockers early and keep technical work tied to outcomes.","lime"]
] as const;
const testimonials = [
  ["NOVA removed the status-meeting tax. Our team now spends that time building, and launches move 32% faster.","Maya Chen","VP Product, Aster Labs","MC"],
  ["The automations feel like another operations teammate. Handoffs happen on time and nothing quietly falls through.","Jordan Ellis","COO, Northstar Studio","JE"],
  ["We finally have one workspace that engineers enjoy and leaders can understand. The visibility is exceptional.","Priya Raman","CTO, Loomline","PR"]
] as const;
const faqs = [
  ["What is NOVA?","NOVA is an AI-powered productivity platform that helps teams plan projects, automate repetitive tasks and collaborate efficiently."],
  ["Do I need technical skills to create automations?","No. Describe the outcome you want or use a visual rule builder. NOVA suggests triggers and actions in plain language."],
  ["Can I use NOVA with my existing tools?","Yes. NOVA is designed to connect with the tools teams already use, keeping updates and handoffs in sync."],
  ["Is my company data secure?","NOVA uses encryption in transit and at rest, role-based permissions and activity logs. Enterprise plans add advanced administrative controls."],
  ["Can I change or cancel my plan?","Yes. You can upgrade, downgrade or cancel at any time. Annual plans remain active through the current billing period."],
  ["Is there a free trial?","Yes. Every team can explore Pro features free for 14 days, with no credit card required."]
] as const;
const plans = [
  {name:"Starter",monthly:0,annual:0,desc:"For individuals organizing their best work.",features:["Up to 3 projects","Core AI assistant","List and board views","1 GB storage"],cta:"Start free"},
  {name:"Pro",monthly:18,annual:14,desc:"For ambitious teams ready to move faster.",features:["Unlimited projects","Advanced AI copilot","Workflow automations","Timeline and insights","Priority support"],cta:"Start 14-day trial",featured:true},
  {name:"Business",monthly:32,annual:25,desc:"For growing organizations that need control.",features:["Everything in Pro","Advanced permissions","Audit logs and SSO","Custom onboarding","Dedicated success manager"],cta:"Contact sales"}
];

function Stat({value,suffix,label}:{value:number;suffix:string;label:string}){const[current,setCurrent]=useState(0);const nodeRef=useRef<HTMLDivElement>(null);useEffect(()=>{const node=nodeRef.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;const start=performance.now();const tick=(now:number)=>{const p=Math.min((now-start)/1200,1);setCurrent(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);observer.disconnect()},{threshold:.4});observer.observe(node);return()=>observer.disconnect()},[value]);return <div ref={nodeRef} className="stat"><strong>{current}{suffix}</strong><span>{label}</span></div>}
function SectionHeading({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <div className="section-heading reveal"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Logo(){return <a className="logo" href="#top" aria-label="NOVA home"><span className="logo-mark"><Command size={19}/></span><span>NOVA</span></a>}

function Nav({dark,setDark}:{dark:boolean;setDark:(v:boolean)=>void}){const[open,setOpen]=useState(false);return <header className="site-header"><nav className="nav shell" aria-label="Main navigation"><Logo/><div className={`nav-links ${open?"open":""}`}>{navLinks.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}<a className="mobile-login" href="#pricing">Log in</a><a className="button small mobile-cta" href="#pricing">Start free <ArrowRight size={16}/></a></div><div className="nav-actions"><button className="icon-button" onClick={()=>setDark(!dark)} aria-label={`Switch to ${dark?"light":"dark"} mode`}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><a className="login" href="#pricing">Log in</a><a className="button small desktop-cta" href="#pricing">Start free <ArrowRight size={16}/></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></nav></header>}

function DashboardPreview(){return <div className="dashboard-wrap reveal"><div className="dashboard-glow"/><div className="dashboard"><div className="dash-sidebar"><Logo/><div className="workspace"><span className="avatar-mini">A</span><span>Atlas team</span><ChevronDown size={14}/></div>{["Overview","My tasks","Projects","Automations"].map((x,i)=><div className={`side-link ${i===0?"active":""}`} key={x}><span className="side-icon"/>{x}</div>)}<div className="side-bottom"><span className="side-icon"/>Invite members</div></div><div className="dash-main"><div className="dash-top"><div><small>Workspace / Overview</small><h3>Good morning, Maya</h3></div><button><span>+</span> New task</button></div><div className="metric-row"><div><span>Tasks completed</span><strong>128</strong><em>+18%</em></div><div><span>Team focus</span><strong>92%</strong><em>+6%</em></div><div><span>Hours saved</span><strong>34h</strong><em>this month</em></div></div><div className="dash-grid"><div className="project-panel"><div className="panel-head"><strong>Launch board</strong><span>This week</span></div><div className="board-cols">{[["TO DO",["Finalize launch copy","Mobile QA pass"]],["IN PROGRESS",["Website redesign","Onboarding flow"]],["DONE",["Analytics setup","Pricing review"]]].map(([title,tasks])=><div className="board-col" key={title as string}><small>{title as string}</small>{(tasks as string[]).map((t,j)=><div className="task" key={t}><i className={`dot d${j}`}/><span>{t}</span><div className="task-meta"><span>{j?"PR":"MC"}</span><Clock3 size={11}/> {j?"Fri":"Today"}</div></div>)}</div>)}</div></div><div className="activity"><div className="panel-head"><strong>AI activity</strong><Sparkles size={15}/></div><p>NOVA organized <b>12 new tasks</b> from your launch notes.</p><div className="ai-line"><CheckCircle2 size={16}/> Owners assigned</div><div className="ai-line"><CheckCircle2 size={16}/> Dates suggested</div><button>Review changes <ArrowRight size={13}/></button></div></div></div></div></div>}
function DemoModal({close}:{close:()=>void}){return <div className="modal-backdrop" onMouseDown={close}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="demo-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close demo"><X/></button><div className="video-placeholder"><div className="play-large"><Play fill="currentColor"/></div><span>2-minute product tour</span></div><h2 id="demo-title">See how work flows in NOVA</h2><p>Turn a project brief into a clear, automated plan—then keep your whole team aligned as work moves forward.</p><button className="button" onClick={close}>Start exploring <ArrowRight size={17}/></button></div></div>}

export default function Home(){
  const[dark,setDark]=useState(false),[annual,setAnnual]=useState(true),[faqOpen,setFaqOpen]=useState(0),[testimonial,setTestimonial]=useState(0),[demo,setDemo]=useState(false),[email,setEmail]=useState(""),[notice,setNotice]=useState(""),[showTop,setShowTop]=useState(false);
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark);const onScroll=()=>setShowTop(window.scrollY>700);window.addEventListener("scroll",onScroll);return()=>window.removeEventListener("scroll",onScroll)},[dark]);
  useEffect(()=>{const els=document.querySelectorAll(".reveal");const ob=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});els.forEach(el=>ob.observe(el));return()=>ob.disconnect()},[]);
  function subscribe(e:FormEvent){e.preventDefault();setNotice(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?"You’re on the list — welcome to NOVA.":"Please enter a valid email address.")}
  return <main id="top"><Nav dark={dark} setDark={setDark}/>
    <section className="hero shell"><div className="hero-copy reveal visible"><div className="announcement"><Sparkles size={15}/> Meet NOVA Intelligence <span>Explore what’s new</span><ArrowRight size={14}/></div><h1>Build better.<br/><span>Work smarter.</span></h1><p>NOVA brings projects, automation and AI into one beautifully simple workspace—so your team can move from idea to impact without the busywork.</p><div className="hero-actions"><a className="button" href="#pricing">Start for free <ArrowRight size={18}/></a><button className="button secondary" onClick={()=>setDemo(true)}><Play size={17} fill="currentColor"/> Watch demo</button></div><div className="hero-note"><Check size={15}/> Free forever plan <Check size={15}/> No credit card required</div></div><DashboardPreview/></section>
    <section className="trusted shell reveal" aria-label="Trusted companies"><p>Trusted by forward-thinking teams at</p><div className="logo-row"><span>Vertex</span><span>Northstar</span><span>QUANT</span><span>Arcwise</span><span>PULSE</span><span>loomline</span></div></section>
    <section className="section shell" id="features"><SectionHeading eyebrow="Everything in one place" title="Less managing. More momentum." text="A focused set of powerful tools that clears the busywork and helps every team do its best work."/><div className="feature-grid">{features.map(([Icon,title,text],i)=><article className="feature-card reveal" style={{transitionDelay:`${i*60}ms`}} key={title}><div className="feature-icon"><Icon/></div><h3>{title}</h3><p>{text}</p><a href="#how-it-works">Learn more <ArrowRight size={15}/></a></article>)}</div></section>
    <section className="section product-section" id="product"><div className="shell split"><div className="product-copy reveal"><span className="eyebrow">Built around your team</span><h2>One source of truth.<br/>Zero work about work.</h2><p>Replace scattered docs, status pings and manual updates with a connected workspace that thinks ahead.</p><ul><li><CheckCircle2/>Give everyone a clear view of priorities</li><li><CheckCircle2/>Turn conversations into assigned action</li><li><CheckCircle2/>Spot blockers before they become delays</li></ul><a className="text-link" href="#solutions">Explore the platform <ArrowRight size={16}/></a></div><div className="product-visual reveal"><div className="orb"><Bot size={34}/><span className="orbit o1"><Check size={14}/></span><span className="orbit o2"><Zap size={14}/></span><span className="orbit o3"><Users2 size={14}/></span></div><div className="float-card fc1"><span>Weekly plan</span><strong>8 tasks prioritized</strong><small><Sparkles size={12}/> Suggested by NOVA AI</small></div><div className="float-card fc2"><span>Team capacity</span><strong>Balanced</strong><div className="capacity"><i/><i/><i/><i/><i/></div></div><div className="float-card fc3"><CheckCircle2/>Launch brief approved</div></div></div></section>
    <section className="section shell" id="how-it-works"><SectionHeading eyebrow="Simple by design" title="From idea to done in three steps" text="NOVA adapts to how your team already works—and makes each step faster."/><div className="steps">{[[MousePointer2,"Bring in your work","Start a project, import existing tasks or describe your goal in plain language."],[Sparkles,"Let AI build the plan","NOVA suggests tasks, owners, timelines and the automations that keep work moving."],[Zap,"Move together","Collaborate in real time while NOVA surfaces progress, risks and next steps."]].map(([Icon,title,text],i)=>{const I=Icon as typeof Zap;return <article className="reveal" key={title as string}><span>0{i+1}</span><div className="step-icon"><I/></div><h3>{title as string}</h3><p>{text as string}</p></article>})}</div></section>
    <section className="stats-section"><div className="shell"><div className="stats-intro reveal"><span className="eyebrow">Momentum you can measure</span><h2>Make more room for meaningful work.</h2></div><div className="stats-grid"><Stat value={12} suffix="k+" label="teams building with NOVA"/><Stat value={42} suffix="%" label="less time spent on admin"/><Stat value={3} suffix="×" label="faster project handoffs"/><Stat value={99} suffix=".9%" label="platform uptime"/></div></div></section>
    <section className="section shell" id="solutions"><SectionHeading eyebrow="Designed for every kind of work" title="One platform. Many ways to move." text="Give every team the structure they need without creating new silos."/><div className="solution-grid">{solutions.map(([Icon,tag,title,text,color])=><article className={`solution-card ${color} reveal`} key={tag}><div className="solution-top"><div className="solution-icon"><Icon/></div><span>{tag}</span></div><h3>{title}</h3><p>{text}</p><a href="#pricing">See the workflow <ArrowRight size={16}/></a></article>)}</div></section>
    <section className="section testimonials"><div className="shell testimonial-layout"><div className="testimonial-intro reveal"><span className="eyebrow">Loved by modern teams</span><h2>Work feels lighter with NOVA.</h2><p>Join teams turning complexity into clear, focused momentum.</p><div className="carousel-controls"><button onClick={()=>setTestimonial((testimonial+testimonials.length-1)%testimonials.length)} aria-label="Previous testimonial"><ChevronLeft/></button><button onClick={()=>setTestimonial((testimonial+1)%testimonials.length)} aria-label="Next testimonial"><ChevronRight/></button></div></div><div className="quote-card reveal"><Quote className="quote-icon"/><blockquote>“{testimonials[testimonial][0]}”</blockquote><div className="person"><span>{testimonials[testimonial][3]}</span><div><strong>{testimonials[testimonial][1]}</strong><small>{testimonials[testimonial][2]}</small></div></div><div className="dots">{testimonials.map((_,i)=><button key={i} className={i===testimonial?"active":""} onClick={()=>setTestimonial(i)} aria-label={`Show testimonial ${i+1}`}/>)}</div></div></div></section>
    <section className="section shell" id="pricing"><SectionHeading eyebrow="Simple, transparent pricing" title="Start small. Scale without limits." text="Try every Pro feature free for 14 days. No credit card required."/><div className="billing-toggle" role="group" aria-label="Billing period"><button className={!annual?"active":""} onClick={()=>setAnnual(false)}>Monthly</button><button className={annual?"active":""} onClick={()=>setAnnual(true)}>Annual <span>Save 20%</span></button></div><div className="pricing-grid">{plans.map(plan=><article className={`price-card reveal ${plan.featured?"featured":""}`} key={plan.name}>{plan.featured&&<div className="popular">Most popular</div>}<h3>{plan.name}</h3><p>{plan.desc}</p><div className="price"><sup>$</sup><strong>{annual?plan.annual:plan.monthly}</strong><span>/ user<br/>/ month</span></div>{annual&&plan.annual>0&&<small className="billed">Billed annually</small>}<a className={`button ${plan.featured?"":"secondary"}`} href="#final-cta">{plan.cta}<ArrowRight size={16}/></a><ul>{plan.features.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></article>)}</div></section>
    <section className="section faq-section" id="faq"><div className="shell faq-layout"><div className="faq-intro reveal"><span className="eyebrow">Common questions</span><h2>Everything you need to know.</h2><p>Can’t find what you’re looking for?</p><a href="mailto:hello@nova.example">Talk to our team <ArrowRight size={15}/></a></div><div className="accordion">{faqs.map(([q,a],i)=><div className={`faq-item reveal ${faqOpen===i?"open":""}`} key={q}><button onClick={()=>setFaqOpen(faqOpen===i?-1:i)} aria-expanded={faqOpen===i}><span>{q}</span><ChevronDown/></button><div className="faq-answer"><p>{a}</p></div></div>)}</div></div></section>
    <section className="final-cta shell" id="final-cta"><div className="cta-glow"/><div className="cta-content reveal"><span className="eyebrow">Your best work starts here</span><h2>Ready to build what’s next?</h2><p>Give your team one place to plan, collaborate and move ideas forward—faster.</p><div className="hero-actions"><a className="button light" href="#pricing">Start for free <ArrowRight size={18}/></a><button className="button ghost" onClick={()=>setDemo(true)}>Book a demo</button></div><small>No credit card required · Free forever plan · Set up in minutes</small></div></section>
    <footer><div className="shell footer-grid"><div className="footer-brand"><Logo/><p>AI-powered productivity for teams that want to spend less time managing work—and more time moving it forward.</p><div className="socials"><a href="#" aria-label="X">𝕏</a><a href="#" aria-label="LinkedIn">in</a><a href="#" aria-label="GitHub">gh</a></div></div>{[["Product","Features","Platform","Pricing","Integrations"],["Solutions","Product","Marketing","Engineering","Operations"],["Company","About","Careers","Contact","Newsroom"]].map(col=><div key={col[0]}><strong>{col[0]}</strong>{col.slice(1).map(x=><a href={x==="Features"?"#features":x==="Pricing"?"#pricing":"#solutions"} key={x}>{x}</a>)}</div>)}<div><strong>Stay in the loop</strong><p>Product news and practical ideas, monthly.</p><form onSubmit={subscribe} noValidate><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" aria-label="Email address"/><button aria-label="Subscribe"><ArrowRight size={17}/></button></form>{notice&&<small className="form-notice" role="status">{notice}</small>}</div></div><div className="shell footer-bottom"><span>© 2026 NOVA, Inc. All rights reserved.</span><div><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Security</a></div></div></footer>
    {showTop&&<button className="back-top" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} aria-label="Back to top"><ArrowUp/></button>}{demo&&<DemoModal close={()=>setDemo(false)}/>}</main>
}
